### ISSUE TITLE
Build error caused by babel version incompatibility

### ISSUE THREAD

**Issue by mindgrub-egottlieb** [preactjs/babel-plugin-transform-hook-names#1]
I added transform-hook-names to my project to try it for the first time, and got the following error during the build. 

```
/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/src/view/utils/hooks/dom.ts: /Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/src/view/utils/hooks/dom.ts: this.input.charCodeAt is not a function
    at Parser.skipSpace (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babylon/lib/index.js:838:27)
    at Parser.nextToken (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babylon/lib/index.js:755:56)
    at Parser.parse (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babylon/lib/index.js:1672:10)
    at Object.parse (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babylon/lib/index.js:7305:37)
    at getAst (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-template/lib/index.js:29:21)
    at /Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-template/lib/index.js:53:24
    at PluginPass.CallExpression (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-plugin-transform-hook-names/src/index.js:32:6)
    at newFn (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-traverse/lib/path/context.js:48:17)from
    at exports.default (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-template/lib/index.js:12:11)
    at module.exports (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-plugin-transform-hook-names/src/index.js:3:25)
    at Function.memoisePluginContainer (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/EGottlieb/Documents/thrive-2.0/web/packages/ui/node_modules/babel-core/lib/transformation/file/index.js:212:65)
```
I found that updating babel from `babel-core@6.26.3` to `@babel/core@7.12.13` (and `babel-plugin-transform-react-jsx@6.24.1` to `@babel/plugin-transform-react-jsx@7.12.13`) made the error go away.

 It would be good to have a minimum babel version for this plugin in the README. Thanks!

**Comment by marvinhagemeister** [comment]
Sorry for the late reponse.

That sounds like a bug with the package manager you're using. This plugin explicitely defines `@babel/core: ^7.12.0` in `peerDependencies`:

https://github.com/preactjs/babel-plugin-transform-hook-names/blob/895965bcac45e99e95b0be688cb73ca72c3aeafb/package.json#L22-L24

This field signals to package managers, that they **must** satisfy that condition. Nonetheless I've added a short note to the README. Thanks for filing an issue 👍
